#!/usr/bin/env bash
source ./setenv.sh server
rmic -d "${ABSPATH2CLASSES}" -classpath ${CLASSPATH} ${JAVAPACKAGEROLE}.${SERVER_CLASS_PREFIX}${SERVANT_IMPL_CLASS_POSTFIX}
rmic -d "${ABSPATH2CLASSES}" -classpath ${CLASSPATH} ${JAVAPACKAGEROLE}.${SERVER_CLASS_PREFIX}${SERVANT_ACTIVATABLE_IMPL_CLASS_POSTFIX}